version: '3.9'
services:
  back-end:
    container_name: prisma_crud_api
    restart: always
    build: .
    ports:
      - 3001:3001
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/prisma-crud-api
  mysql:
    container_name: prisma_crud_api_db
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_USER_PASSWORD: root
      MYSQL_ROOT_PASSWORD: password
  