version: '3.9'
services:
  back-end:
    container_name: prisma_crud_api
    restart: always
    build: .
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/prisma-crud-api
  db:
    container_name: prisma_crud_api_db
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  
